/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hari
 */
public class ViewBillRegisterAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ViewBillRegisterAdmin
     */
    
    public ViewBillRegisterAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cb_option = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        b_proceed = new javax.swing.JButton();
        t_studentid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mc_month = new com.toedter.calendar.JMonthChooser();
        y_year = new com.toedter.calendar.JYearChooser();
        b_fetchstudentbill = new javax.swing.JButton();
        b_fetchmonthbill = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_register = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bill Payment Register");
        setResizable(false);

        jLabel1.setText("Select An Option");

        cb_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View Common Bill of a Month", "View Special Bills Of A Student", "View overall Bill Status Of A Month" }));

        jLabel2.setText("Enter Student ID");

        b_proceed.setText("Proceed");
        b_proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_proceedActionPerformed(evt);
            }
        });

        t_studentid.setEnabled(false);

        jLabel3.setText("Enter Month And Year");

        mc_month.setEnabled(false);

        y_year.setEnabled(false);

        b_fetchstudentbill.setText("Fetch Bill");
        b_fetchstudentbill.setEnabled(false);
        b_fetchstudentbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fetchstudentbillActionPerformed(evt);
            }
        });

        b_fetchmonthbill.setText("Fetch Bill");
        b_fetchmonthbill.setEnabled(false);
        b_fetchmonthbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fetchmonthbillActionPerformed(evt);
            }
        });

        jLabel4.setText("Requested Bill Register");

        t_register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_register);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_option, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_studentid, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mc_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y_year, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_proceed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_fetchstudentbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_fetchmonthbill, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_proceed))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_studentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_fetchstudentbill))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(mc_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_fetchmonthbill))
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_proceedActionPerformed
        // TODO add your handling code here:
        option=cb_option.getItemAt(cb_option.getSelectedIndex());
        if(option.equals("View Common Bill of a Month")||option.equals("View overall Bill Status Of A Month"))
        {
            mc_month.setEnabled(true);
            y_year.setEnabled(true);
            b_fetchmonthbill.setEnabled(true);
            t_studentid.setEnabled(false);
            b_fetchstudentbill.setEnabled(false);
        }
        else
        {
            mc_month.setEnabled(false);
            y_year.setEnabled(false);
            b_fetchmonthbill.setEnabled(false);
            t_studentid.setEnabled(true);
            b_fetchstudentbill.setEnabled(true);
            
        }
    }//GEN-LAST:event_b_proceedActionPerformed

    private void b_fetchstudentbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fetchstudentbillActionPerformed
        // TODO add your handling code here:
        String userid=t_studentid.getText();
        try
        {
        con = new Connector().getCon();
        stmt=con.prepareStatement("SELECT * FROM proj.SPECIAL_BILL_REG WHERE USERID= ?;");
        stmt.setString(1,userid);
        ResultSet rs=stmt.executeQuery();
        t_register.setModel(DbUtils.resultSetToTableModel(rs));
        if(!rs.first())
        {
              JOptionPane.showMessageDialog(null, "No data found");         
        }
              
         
     } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } finally {
            try {
                if(con!=null) con.close();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
            }
            
            try {
                if(stmt!=null) stmt.close();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
            }
        }
        
        
    }//GEN-LAST:event_b_fetchstudentbillActionPerformed

    private void b_fetchmonthbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fetchmonthbillActionPerformed
        // TODO add your handling code here:
        String monthname[]={"JANUARY","FEBRUARY","MARCH","APRIL","MAY","JUNE","JULY","AUGUST","SEPTEMBER","OCTOBER","NOVEMBER","DECEMBER"};
        int m=mc_month.getMonth();
        int year=y_year.getYear();
        String month=monthname[m];
        

        try
        {
            con = new Connector().getCon();
            if(option.equals("View Common Bill of a Month"))
            {
                stmt=con.prepareStatement("SELECT * FROM proj.COMMON_MESS_BILL WHERE MONTH=? AND YEAR=?;");
                stmt.setString(2,Integer.toString(year));
            }
            else 
                if(option.equals("View overall Bill Status Of A Month"))
                    stmt=con.prepareStatement("SELECT USER_ID,? FROM proj.OVERALL_BILL_STATUS;");
            
            stmt.setString(1,month);
            ResultSet rs=stmt.executeQuery();
            t_register.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first())
            {
                  JOptionPane.showMessageDialog(null, "No data found");         
            }
         
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Class Missing. Contact System Admin.");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Unknown Error. Contact System Admin.");
        } finally {
            try {
                if(con!=null) con.close();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
            }
            
            try {
                if(stmt!=null) stmt.close();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
            }
        }
        
    }//GEN-LAST:event_b_fetchmonthbillActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewBillRegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewBillRegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewBillRegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewBillRegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewBillRegisterAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_fetchmonthbill;
    private javax.swing.JButton b_fetchstudentbill;
    private javax.swing.JButton b_proceed;
    private javax.swing.JComboBox<String> cb_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JMonthChooser mc_month;
    private javax.swing.JTable t_register;
    private javax.swing.JTextField t_studentid;
    private com.toedter.calendar.JYearChooser y_year;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement stmt=null;
    private String option;
}
