package projecttemp;
import java.sql.*;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hari
 */
public class Home_OutgoingRegister extends javax.swing.JFrame {

    /**
     * Creates new form Home_OutgoingRegister
     */
    private static int flag=1;
    String userid;
    public Home_OutgoingRegister(String id) {
        userid=id;
        initComponents();
        if(flag==1)
       {
           flag=0;
           
           dofunction();
       }
       fetch();
    }
    public void fetch()
   {
     try
     {
         Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost/?user=hari&password=ubuntupassword");
         Statement st=con.createStatement();
         PreparedStatement pst=con.prepareStatement("select DATE_TIME_OUT,HOME_OUT,PLACE from proj.HOME_OUT_REG where USER_ID= ? and DATE_TIME_IN= ? ;");
         pst.setString(1,userid);
         pst.setString(2, "0");
         ResultSet rs=pst.executeQuery();
         t_register.setModel(DbUtils.resultSetToTableModel(rs));
         
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null, e);
     }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setResizable(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_option = new javax.swing.JComboBox<>();
        b_checkout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_place = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_register = new javax.swing.JTable();
        b_checkin = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home Going/ Out Going Register");

        jLabel2.setText("Select Your Option");

        cb_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home Going", "Out Going" }));
        cb_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_optionActionPerformed(evt);
            }
        });

        b_checkout.setText("Check Out Now");
        b_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_checkoutActionPerformed(evt);
            }
        });

        jLabel5.setText("Place");


        jLabel6.setText("Check Out Form");

        jLabel7.setText("Check In Form");

        t_register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Date & Time", "Home/Out", "Place"
            }
        ));
        t_register.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(t_register);

        b_checkin.setText("Check In Now");
        b_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_checkinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_place, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b_checkout)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(184, 184, 184))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(b_checkin)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_option, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(b_checkout)
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(b_checkin)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void b_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_checkoutActionPerformed
        // TODO add your handling code here:
        try
        {
        String number="1";
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm dd-MM-yyyy ");  
        LocalDateTime now = LocalDateTime.now();  
        String today=dtf.format(now); 
        String opt=cb_option.getItemAt(cb_option.getSelectedIndex());
        String place=tf_place.getText();
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/?user=hari&password=ubuntupassword");
        Statement st=con.createStatement();
        PreparedStatement stmt=con.prepareStatement("INSERT INTO `proj`.`HOME_OUT_REG` (`USER_ID`, `DATE_TIME_OUT`, `HOME_OUT`,`PLACE`,`DATE_TIME_IN`) VALUES (?, ?, ?, ?, ?);");
        stmt.setString(1,userid);
        stmt.setString(2,today);
        stmt.setString(3,opt);
        stmt.setString(4,place);
        stmt.setString(5,"0");
        int flag2 = stmt.executeUpdate();
        if(flag2==1)
            JOptionPane.showMessageDialog(null,"Checked Out Succesfully");
        stmt.close();
        con.close();
        }
        catch(SQLException s)
            {
                System.out.println("SQL Exception "+s.getStackTrace()[0].getLineNumber()+s.getMessage());
            }catch(Exception e)
            {
                System.out.println("Exception "+e.toString());
            }
            fetch();
    }//GEN-LAST:event_b_checkoutActionPerformed

    private void cb_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_optionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_optionActionPerformed

    private void b_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_checkinActionPerformed
        // TODO add your handling code here:
        try
        {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm dd-MM-yyyy ");  
        LocalDateTime now = LocalDateTime.now();  
        String today=dtf.format(now); 
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/?user=hari&password=ubuntupassword");
        Statement st=con.createStatement();
        PreparedStatement stmt=con.prepareStatement("update proj.HOME_OUT_REG set DATE_TIME_IN = ? where USER_ID= ? ");
        stmt.setString(1,today);
        stmt.setString(2,userid);
        int flag1 = stmt.executeUpdate();
        System.out.println(flag1);
            JOptionPane.showMessageDialog(null,"Checked In successfully");
        stmt.close();
        con.close();
        fetch();
        }
        catch(Exception e)
        {
            System.out.println("Exception "+e.toString());
        }
        
    }//GEN-LAST:event_b_checkinActionPerformed

    /**
     * @param args the command line arguments
     */
    public void dofunction() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_OutgoingRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_OutgoingRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_OutgoingRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_OutgoingRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_OutgoingRegister(userid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_checkin;
    private javax.swing.JButton b_checkout;
    private javax.swing.JComboBox<String> cb_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable t_register;
    private javax.swing.JTextField tf_place;
    // End of variables declaration//GEN-END:variables
}
