/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmsadmin;

import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author rr1
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    String id;
    public AdminDashboard(String userid) {
        id=userid;
        initComponents();
        tf_welcomemessage.setText("Welcome "+id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_welcome = new javax.swing.JLabel();
        b_homeoutregister = new javax.swing.JButton();
        b_complaintregister = new javax.swing.JButton();
        b_suggestions = new javax.swing.JButton();
        b_messmenu = new javax.swing.JButton();
        b_hostelvacaterequet = new javax.swing.JButton();
        b_studentslookup = new javax.swing.JButton();
        b_messreduction = new javax.swing.JButton();
        b_messbill = new javax.swing.JButton();
        b_contactinamtes = new javax.swing.JButton();
        b_logout = new javax.swing.JButton();
        b_assignhs = new javax.swing.JButton();
        b_updatemessbill = new javax.swing.JButton();
        b_addadmin = new javax.swing.JButton();
        tf_welcomemessage = new javax.swing.JLabel();
        b_myprofile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Dashboard");
        setResizable(false);

        l_welcome.setText("Select any one of the below options to continue");

        b_homeoutregister.setText("Homegoing/Outgoing Registeer");
        b_homeoutregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_homeoutregisterActionPerformed(evt);
            }
        });

        b_complaintregister.setText("Complaint Register");
        b_complaintregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_complaintregisterActionPerformed(evt);
            }
        });

        b_suggestions.setText("Suggestions Register");
        b_suggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_suggestionsActionPerformed(evt);
            }
        });

        b_messmenu.setText("View/Change Mess Menu");
        b_messmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_messmenuActionPerformed(evt);
            }
        });

        b_hostelvacaterequet.setText("Hostel Vacate/Room Change Request");
        b_hostelvacaterequet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hostelvacaterequetActionPerformed(evt);
            }
        });

        b_studentslookup.setText("Students Lookup");
        b_studentslookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_studentslookupActionPerformed(evt);
            }
        });

        b_messreduction.setText("Mess Reduction Requests");
        b_messreduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_messreductionActionPerformed(evt);
            }
        });

        b_messbill.setText("Mess Bill Register");
        b_messbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_messbillActionPerformed(evt);
            }
        });

        b_contactinamtes.setText("Contact Inmates");
        b_contactinamtes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_contactinamtesActionPerformed(evt);
            }
        });

        b_logout.setText("Logout");
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });

        b_assignhs.setText("Add/Remove HS");
        b_assignhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_assignhsActionPerformed(evt);
            }
        });

        b_updatemessbill.setText("Add/Update Mess Bill");
        b_updatemessbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updatemessbillActionPerformed(evt);
            }
        });

        b_addadmin.setText("Add New Admin");
        b_addadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addadminActionPerformed(evt);
            }
        });

        tf_welcomemessage.setText("Welcome User!");

        b_myprofile.setText("MyProfile");
        b_myprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_myprofileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tf_welcomemessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_myprofile)
                .addGap(41, 41, 41)
                .addComponent(b_logout)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b_addadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_assignhs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_homeoutregister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_complaintregister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_suggestions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_messmenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_hostelvacaterequet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_studentslookup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_messreduction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_messbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_contactinamtes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_updatemessbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(l_welcome)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_logout)
                        .addComponent(b_myprofile))
                    .addComponent(tf_welcomemessage))
                .addGap(34, 34, 34)
                .addComponent(l_welcome)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_homeoutregister, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_hostelvacaterequet, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_studentslookup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_complaintregister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_suggestions, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_messreduction, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_messbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_messmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_updatemessbill, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_addadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_contactinamtes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_assignhs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_complaintregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_complaintregisterActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplaintRegisterAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_complaintregisterActionPerformed

    private void b_studentslookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_studentslookupActionPerformed
        // TODO add your handling code here: 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLookupAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_studentslookupActionPerformed

    private void b_homeoutregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_homeoutregisterActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeOutGoingAdmin().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_b_homeoutregisterActionPerformed

    private void b_hostelvacaterequetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hostelvacaterequetActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VacateChangeAdmin().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_b_hostelvacaterequetActionPerformed

    private void b_suggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_suggestionsActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuggestionsAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_suggestionsActionPerformed

    private void b_messreductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_messreductionActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessReductionAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_messreductionActionPerformed

    private void b_messmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_messmenuActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessMenuAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_messmenuActionPerformed

    private void b_messbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_messbillActionPerformed
        // TODO add your handling code here:
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillRegister().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_messbillActionPerformed

    private void b_updatemessbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updatemessbillActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMessBill().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_updatemessbillActionPerformed

    private void b_assignhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_assignhsActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignHSAdmin().setVisible(true);
            }
        });
    }//GEN-LAST:event_b_assignhsActionPerformed

    private void b_contactinamtesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_contactinamtesActionPerformed
        // TODO add your handling code here:
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactInmatesAdmin(id).setVisible(true);
            }
        });
    }//GEN-LAST:event_b_contactinamtesActionPerformed

    private void b_addadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addadminActionPerformed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationWindowAdmin().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_b_addadminActionPerformed

    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logged out Succesfully");
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_b_logoutActionPerformed

    private void b_myprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_myprofileActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfileAdmin(id).setVisible(true);
            }
        });
    }//GEN-LAST:event_b_myprofileActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDashboard(id).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_addadmin;
    private javax.swing.JButton b_assignhs;
    private javax.swing.JButton b_complaintregister;
    private javax.swing.JButton b_contactinamtes;
    private javax.swing.JButton b_homeoutregister;
    private javax.swing.JButton b_hostelvacaterequet;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton b_messbill;
    private javax.swing.JButton b_messmenu;
    private javax.swing.JButton b_messreduction;
    private javax.swing.JButton b_myprofile;
    private javax.swing.JButton b_studentslookup;
    private javax.swing.JButton b_suggestions;
    private javax.swing.JButton b_updatemessbill;
    private javax.swing.JLabel l_welcome;
    private javax.swing.JLabel tf_welcomemessage;
    // End of variables declaration//GEN-END:variables
}
